Structure: Ducks

Models:
  - Student:

    Slice:
      - name: string
      - phone: number
      - address: string

    Thunks:
      - getName:
          - /api/name
          - getName

  - Campus:

    Slice:
      - name: string
      - phone: number
      - address: string

    Thunks:
      - getCampus:
          - /api/campus
          - getCampus
# Want to edit this file?
# Be careful! Make sure that models and properties always have a
# space between the dash and the name. Major fields
# (Models, Actions, Thunks, CRUD) should all have a colon after them.
# Also, the name of this file **must** be lamp.config.yaml or the code will not run.
#
# This is how your file should look:
#
# Structure: Ducks
#
# Models:
#
# - Ducks:
#
#      - feathers: number
#
#    CRUD: false
#
#     Actions:
#      - migrateSouth
#      - flyTogether
#
